# Generated by Django 4.1 on 2024-05-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod', models.OneToOneField(db_column='cod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.persona')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
