# Generated by Django 4.1 on 2024-05-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod',
            field=models.OneToOneField(db_column='cod', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.persona'),
        ),
    ]
