# Generated by Django 4.1 on 2024-05-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_domiciliario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domiciliario',
            old_name='disponible',
            new_name='atendiendo',
        ),
    ]
