# Generated by Django 4.1 on 2024-05-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='cod_cliente',
            new_name='cod_per',
        ),
        migrations.AlterUniqueTogether(
            name='direccion',
            unique_together={('cod_per', 'dir')},
        ),
    ]
