# Generated by Django 4.1 on 2024-05-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_cod_cliente_direccion_cod_per_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.BigIntegerField()),
                ('cod_per', models.ForeignKey(db_column='cod_per', on_delete=django.db.models.deletion.CASCADE, to='polls.persona')),
            ],
            options={
                'db_table': 'telefono',
                'unique_together': {('cod_per', 'telefono')},
            },
        ),
    ]
