# Generated by Django 4.1 on 2024-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_categoria_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
