# Generated by Django 4.1 on 2024-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
