# Generated by Django 4.1 on 2024-05-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_producto_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(db_column='cod_cliente', on_delete=django.db.models.deletion.CASCADE, to='polls.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('cod', models.OneToOneField(db_column='cod', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.pedido')),
                ('hora_envio', models.CharField(blank=True, max_length=5, null=True)),
                ('hora_entrega', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_domiciliario', models.OneToOneField(db_column='cod_domiciliario', on_delete=django.db.models.deletion.CASCADE, to='polls.domiciliario')),
            ],
            options={
                'db_table': 'domicilio',
            },
        ),
    ]
