# Generated by Django 4.1 on 2024-05-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_pedido_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='products',
            field=models.ManyToManyField(through='polls.Detalle', to='polls.producto'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='cod_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pedido'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='cod_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detalle',
            unique_together={('cod_pedido', 'cod_producto')},
        ),
    ]
