# Generated by Django 4.1 on 2024-05-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_detalle_pedido_products_detalle_cod_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dom', models.ForeignKey(db_column='cod_dom', on_delete=django.db.models.deletion.CASCADE, to='polls.domiciliario')),
            ],
            options={
                'db_table': 'asignacion',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='domiciliarios',
            field=models.ManyToManyField(through='polls.Asignacion', to='polls.domiciliario'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='seq_hor',
            field=models.ForeignKey(db_column='seq_hor', on_delete=django.db.models.deletion.CASCADE, to='polls.horario'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('cod_dom', 'seq_hor')},
        ),
    ]
