# Generated by Django 4.1 on 2024-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_asignacion_horario_domiciliarios_asignacion_seq_hor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='seq',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
