# Generated by Django 4.1 on 2024-06-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_domicilio_cod_domiciliario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='cod_per',
            field=models.ForeignKey(db_column='cod_per', on_delete=django.db.models.deletion.CASCADE, to='polls.persona'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='cod',
            field=models.OneToOneField(db_column='cod', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.persona'),
        ),
    ]
